### ISSUE TITLE
regex error when brackets in test title

### ISSUE THREAD

**Issue by chenchaoyi** [TestArmada/magellan-mocha-plugin#9]
The following test will be marked as PASS in magellan:

```
var expect = require('chai').expect;

describe('description....', function () {

  it('test title (ohno)', function () {
    expect(true).to.equal(false);
  });

});
```

```
$ ./node_modules/.bin/magellan  --serial --max_test_attempts=1
Magellan 8.7.1
Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/cchen21/WEC/misc/chico-e2e/magellan.json
Magellan is creating temporary files at: /Users/cchen21/WEC/misc/chico-e2e/temp
Sauce configuration OK

Running 1 tests in serial mode with nodejs

--> Serial mode, mock port:12000, running test: description.... test title (ohno) @nodejs


  0 passing (3ms)


(1 / 1) PASS  description.... test title (ohno) @nodejs

Checking for zombie processes...
No zombies found.

============= Suite Complete =============

     Status: PASSED
    Runtime: 4.8s
Total tests: 1
 Successful: 1 / 1
```

The following test is giving regex parsing error:

```
var expect = require('chai').expect;

describe('description....', function () {

  it('test title (ohno', function () {
    expect(true).to.equal(false);
  });

});
```

```
$ ./node_modules/.bin/magellan  --serial --max_test_attempts=1
Magellan 8.7.1
Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/cchen21/WEC/misc/chico-e2e/magellan.json
Magellan is creating temporary files at: /Users/cchen21/WEC/misc/chico-e2e/temp
Sauce configuration OK

Running 1 tests in serial mode with nodejs

--> Serial mode, mock port:12000, running test: description.... test title (ohno @nodejs
/Users/cchen21/WEC/misc/chico-e2e/node_modules/mocha/bin/_mocha:256
if (program.grep) mocha.grep(new RegExp(program.grep));
                             ^

SyntaxError: Invalid regular expression: /description\.\.\.\. test title (ohno/: Unterminated group
    at new RegExp (native)
    at Object.<anonymous> (/Users/cchen21/WEC/misc/chico-e2e/node_modules/mocha/bin/_mocha:256:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

(1 / 1) FAIL  description.... test title (ohno @nodejs

Checking for zombie processes...
No zombies found.

============= Failed Tests:  =============


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Failed Test: description.... test title (ohno @nodejs
 # attempts: 1
     output:
17:30:29 /Users/cchen21/WEC/misc/chico-e2e/node_modules/mocha/bin/_mocha:256
17:30:29 if (program.grep) mocha.grep(new RegExp(program.grep));
17:30:29                              ^
17:30:29 SyntaxError: Invalid regular expression: /description\.\.\.\. test title (ohno/: Unterminated group
17:30:29     at new RegExp (native)
17:30:29     at Object.<anonymous> (/Users/cchen21/WEC/misc/chico-e2e/node_modules/mocha/bin/_mocha:256:30)
17:30:29     at Module._compile (module.js:409:26)
17:30:29     at Object.Module._extensions..js (module.js:416:10)
17:30:29     at Module.load (module.js:343:32)
17:30:29     at Function.Module._load (module.js:300:12)
17:30:29     at Function.Module.runMain (module.js:441:10)
17:30:29     at startup (node.js:139:18)
17:30:29     at node.js:968:3



============= Suite Complete =============

     Status: FAILED
    Runtime: 4.8s
Total tests: 1
 Successful: 0 / 1
     Failed: 1 / 1
```

While the following test is marked as failed as expected:

```
var expect = require('chai').expect;

describe('description....', function () {

  it('test title ohno', function () {
    expect(true).to.equal(false);
  });

});
```

```
$ ./node_modules/.bin/magellan  --serial --max_test_attempts=1
Magellan 8.7.1
Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/cchen21/WEC/misc/chico-e2e/magellan.json
Magellan is creating temporary files at: /Users/cchen21/WEC/misc/chico-e2e/temp
Sauce configuration OK

Running 1 tests in serial mode with nodejs

--> Serial mode, mock port:12000, running test: description.... test title ohno @nodejs


  description....
    1) test title ohno


  0 passing (11ms)
  1 failing

  1) description.... test title ohno:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (try/credit-card.js:6:21)




(1 / 1) FAIL  description.... test title ohno @nodejs

Checking for zombie processes...
No zombies found.

============= Failed Tests:  =============


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Failed Test: description.... test title ohno @nodejs
 # attempts: 1
     output:
17:31:19   description....
17:31:19     1) test title ohno
17:31:19   0 passing (11ms)
17:31:19   1 failing
17:31:19   1) description.... test title ohno:
17:31:19       AssertionError: expected true to equal false
17:31:19       + expected - actual
17:31:19       -true
17:31:19       +false
17:31:19       at Context.<anonymous> (try/credit-card.js:6:21)



============= Suite Complete =============

     Status: FAILED
    Runtime: 4.8s
Total tests: 1
 Successful: 0 / 1
     Failed: 1 / 1
```

Originally found by @william-chen

**Comment by chenchaoyi** [comment]
fixed by #10
